### ISSUE TITLE
i18n format error messages with react-intl

### ISSUE THREAD

**Issue by VincentCordobes** [theadam/react-inform#2]
Hi,
I am trying to use the **formatMessage** function from **react-intl v2** to display error messages.
This function is injected to a component with injectIntl(), we can then access it via props.
Since error strings are hard coded in the form decorator, do you have any advise to make it works with react-intl ?

**Comment by theadam** [comment]
Take a look at this example: https://jsfiddle.net/theadam/d0hypvtz/3/.

Since you have control of the validate function, there's no reason you cant return something other than strings there.  Here I am returning a react-intl MessageDescriptor instead of strings.  

Notice in the `email` field, you even have a chance to pass in `values` so that react-intl can fill in some placeholders.

Let me know if this solution will work for you!

**Comment by VincentCordobes** [comment]
Oh It works well indeed when the validate function returns an object.
Thank you for your quick reply and the code snippet.
Very well designed lib btw.

**Comment by theadam** [comment]
Thanks! I think I might add a react-intl example, just to show some flexibility!  Thanks for the idea!
